package com.tunde.loanworkflow.model;
public class Applicant {
    private int id;
    private String name;
    private String email;
    private double accountBalance;
    private double approvedLoanAmount;
    private String createdAt;

    public Applicant() {}

    public Applicant(String name, String email, double accountBalance, double approvedLoanAmount) {
        this.name = name;
        this.email = email;
        this.accountBalance = accountBalance;
        this.approvedLoanAmount = approvedLoanAmount;
    }

    public Applicant(int id, String name, String email, double accountBalance, double approvedLoanAmount, String createdAt) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.accountBalance = accountBalance;
        this.approvedLoanAmount = approvedLoanAmount;
        this.createdAt = createdAt;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public double getAccountBalance() {
        return accountBalance;
    }

    public void setAccountBalance(double accountBalance) {
        this.accountBalance = accountBalance;
    }

    public double getApprovedLoanAmount() {
        return approvedLoanAmount;
    }

    public void setApprovedLoanAmount(double approvedLoanAmount) {
        this.approvedLoanAmount = approvedLoanAmount;
    }

    public String getCreatedAt() { //No setters for fields auto generated by MySQL
        return createdAt;
    }
    
    @Override
    public String toString() {
        return "Applicant{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", accountBalance=" + accountBalance +
                ", approvedLoanAmount=" + approvedLoanAmount +
                ", createdAt='" + createdAt + '\'' +
                '}';
    }
}